# fly.toml app configuration file generated for miniflux-fly-app on 2025-02-05T22:33:28+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miniflux-fly-app'
primary_region = 'lax'

[build]
  image = 'docker.io/miniflux/miniflux:latest'

[env]
  BASE_URL = 'https://r.yejun.dev'
  CREATE_ADMIN = 'true'
  HTTPS = 'true'
  PORT = '8080'
  RUN_MIGRATIONS = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
