# fly.toml app configuration file generated for miniflux-fly-lively-rain-5224 on 2025-01-24T13:19:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'miniflux-fly-lively-rain-5224'
primary_region = 'lax'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[build]
  image = 'docker.io/miniflux/miniflux:latest'

[env]
  RUN_MIGRATIONS = 'true'
  CREATE_ADMIN = 'true'
  HTTPS = 'true'
  PORT = '8080'
  BASE_URL = 'https://r.yejun.dev'
